[package]
name = "zokrates_stdlib"
version = "0.1.0"
authors = ["schaeff <thibaut@schaeff.fr>", "Stefan Deml <stefandeml@gmail.com>"]
edition = "2018"

[features]
default = ["libsnark"]
libsnark = ["zokrates_core/libsnark"]

[dev-dependencies]
zokrates_field = { version = "0.3", path = "../zokrates_field" }
zokrates_core = { version = "0.3", path = "../zokrates_core" }
zokrates_fs_resolver = { version = "0.4", path = "../zokrates_fs_resolver" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
glob = "0.3.0"
