[package]
name = "code_to_r1cs"
version = "0.1.0"
authors = ["Dennis Kuhnert <mail@kyroy.com>"]
build = "build.rs"

[dependencies]
regex = "0.2"
libc = "0.2.0"

[build-dependencies]
gcc = "0.3.41"
