[package]
name = "code_to_r1cs"
version = "0.1.0"
authors = ["Dennis Kuhnert <mail@kyroy.com>"]
build = "build.rs"

[features]
nolibsnark = []

[dependencies]
libc = "0.2.0"
num = "0.1.36"
lazy_static = "0.1.*"

[build-dependencies]
gcc = "0.3.41"
