[target.x86_64-apple-darwin.env]
passthrough = [
    "CRATE_NAME",
    "LDFLAGS",
    "CPPFLAGS",
    "PKG_CONFIG_PATH",
]

[target.x86_64-unknown-linux-gnu.env]
passthrough = [
    "CRATE_NAME",
    "LDFLAGS",
    "CPPFLAGS",
    "PKG_CONFIG_PATH",
]