[package]
name = "zokrates_embed"
version = "0.1.0"
authors = ["schaeff <thibaut@schaeff.fr>"]
edition = "2018"

[dependencies]
sapling-crypto_ce = { version =  "0.0.5", default-features = false }
bellman_ce = { version = "0.3.0", features=["wasm"], default-features = false }
