[package]
name = "zokrates_embed"
version = "0.1.0"
authors = ["schaeff <thibaut@schaeff.fr>"]
edition = "2018"

[dependencies]
bellman_ce = { version = "0.3.0", default-features = false, features = ["wasm"] }
sapling-crypto_ce = { git = "https://github.com/dark64/sapling-crypto", branch = "master", default-features = false }