[package]
name = "zokrates_field"
version = "0.3.4"
authors = ["Thibaut Schaeffer <thibaut@schaeff.fr>", "Guillaume Ballet <gballet@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.4"
bincode = "0.8.0"
serde_json = "1.0"
num-traits = "0.2"
num-integer = "0.1"
bellman_ce = "0.3"
sha2 = "0.8.0"

[dependencies.num-bigint]
version = "0.2"
features = ["serde"]

[dev-dependencies]
rand = "0.4"
