[package]
name = "zokrates_macro"
version = "0.1.0"
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
log = "0.4"
cfg-if = "0.1"

[lib]
proc-macro = true

[features]
default = []
wasm = []
