[package]
name = "zokrates_abi"
version = "0.1.0"
authors = ["thibaut"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zokrates_field = { version = "0.3", path = "../zokrates_field" }
zokrates_core = { version = "0.3", path = "../zokrates_core" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
