name: Pull request changelog check
on: [pull_request]
jobs:
  build:
    name: Run changelog check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Changelog check
        if: ${{ !(contains(github.event.pull_request.labels.*.name, 'changelog-not-required'))}}
        run: ./scripts/changelog-check.sh